version: "3.9"

services:
  # NATS Service
  nats:
    image: nats:2.10-alpine
    container_name: transactmesh-nats

    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"

    ports:
      - "4222:4222"
      - "8222:8222"

    volumes:
      - nats-data:/data

    networks:
      - transactmesh-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres Service
  postgres:
    image: postgres:16-alpine
    container_name: transactmesh-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transactmesh

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - transactmesh-network

    restart: unless-stopped

    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=128MB"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: transactmesh-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - transactmesh-network

    restart: unless-stopped

    command: ["redis-server", "--appendonly", "yes"]

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Loki Service
  loki:
    image: grafana/loki:3.0.0
    container_name: transactmesh-loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./infra/observability/loki.yml:/etc/loki/config.yml
    networks:
      - transactmesh-network
    restart: unless-stopped

  # Tempo Service
  tempo:
    image: grafana/tempo:2.5.0
    container_name: transactmesh-tempo
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./infra/observability/tempo.yml:/etc/tempo.yml
    networks:
      - transactmesh-network
    restart: unless-stopped

  # mimir Service
  mimir:
    image: grafana/mimir:latest
    container_name: transactmesh-mimir
    command:
      - "-config.file=/etc/mimir.yml"
    ports:
      - "9009:9009"
    volumes:
      - ./infra/observability/mimir.yml:/etc/mimir.yml
    networks:
      - transactmesh-network
    restart: unless-stopped

  # Granafa Service
  grafana:
    image: grafana/grafana:latest
    container_name: transactmesh-grafana

    ports:
      - "3001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password

    secrets:
      - grafana_admin_password

    networks:
      - transactmesh-network

    restart: unless-stopped

networks:
  transactmesh-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  nats-data:
