multitenancy_enabled: false

server:
  http_listen_port: 9009

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/blocks

compactor:
  data_dir: /tmp/mimir/compactor

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  ring:
    replication_factor: 1
    kvstore:
      store: inmemory

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

store_gateway:
  sharding_ring:
    replication_factor: 1
